#!/bin/sh

#  _                                 
# | |__  ___ _ ____      ___ __ ___  
# | '_ \/ __| '_ \ \ /\ / / '_ ` _ \ 
# | |_) \__ \ |_) \ V  V /| | | | | |
# |_.__/|___/ .__/ \_/\_/ |_| |_| |_|
#           |_|                      
#

bm() { bspc monitor "$@" & }
bc() { bspc config "$@" & }
br() { bspc rule -a "$@" & }
bs() { pkill -x "$1"; { sleep 0.1; "$@" & }; }

bm HDMI-0 -d 1 2 3 4 5
bm HDMI-1 -d 6 7 8 9 10

bc focus_follows_pointer true
bc pointer_follows_focus false
bc pointer_follows_monitor true

bc border_width 5
bc window_gap 10
# bc top_padding 40

bc split_ratio 0.5
# bspc config borderless_monocle true
# bspc config gapless_monocle true

br Pavucontrol state=floating
br feh state=floating
br firefox desktop='1'
br code desktop='2' follow=off
br Lens desktop='4' follow=off
br discord desktop='5' follow=off
br chromium desktop='6' follow=off
br kitty:scratchpad monitor='HDMI-0' state=floating layer=above sticky=on rectangle=1500x600+1170+570

color_gray_2="#C3BAC6"
color_red="#F28FAD"
color_yellow="#FAE3B0"

bc normal_border_color $color_gray_2
bc active_border_color $color_gray_2
bc focused_border_color $color_red
bc presel_feedback_color $color_yellow

# fix cursor size
xsetroot -cursor_name left_ptr

bs sxhkd
bs picom --config ~/.config/picom.conf
bs dunst
bs playerctld daemon
. "${HOME}/.fehbg" &
. "${HOME}/.config/polybar/launch.sh" &

