#!/bin/sh

#  _                                 
# | |__  ___ _ ____      ___ __ ___  
# | '_ \/ __| '_ \ \ /\ / / '_ ` _ \ 
# | |_) \__ \ |_) \ V  V /| | | | | |
# |_.__/|___/ .__/ \_/\_/ |_| |_| |_|
#           |_|                      
#

bspc monitor HDMI-0 -d 1 2 3 4 5
bspc monitor DP-0 -d 6 7 8 9 10

bspc config focus_follows_pointer true
bspc config pointer_follows_focus false
bspc config pointer_follows_monitor true

bspc config border_width 4
bspc config window_gap 15
bspc config top_padding 40

bspc config split_ratio 0.5
# bspc config borderless_monocle true
# bspc config gapless_monocle true

bspc rule -a Pavucontrol state=floating
bspc rule -a feh state=floating
bspc rule -a firefox desktop='^1'
bspc rule -a chromium desktop='^6' follow=off
bspc rule -a discord desktop='^5' follow=off
bspc rule -a code desktop='^3' follow=off
bspc rule -a kitty:scratchpad monitor='HDMI-0' state=floating layer=above sticky=on rectangle=1500x600+1170+70

color_gray_2="#C3BAC6"
color_red="#F28FAD"
color_yellow="#FAE3B0"

bspc config normal_border_color $color_gray_2
bspc config active_border_color $color_gray_2
bspc config focused_border_color $color_red
bspc config presel_feedback_color $color_yellow

# fix cursor size
xsetroot -cursor_name left_ptr

pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x picom > /dev/null || picom --config ~/.config/picom.conf &
pgrep -x dunst > /dev/null || dunst &
pgrep -x playerctld > /dev/null || playerctld daemon &
. "${HOME}/.fehbg" &
. "${HOME}/.config/polybar/launch.sh" &

