#!/bin/sh

#  _                                 
# | |__  ___ _ ____      ___ __ ___  
# | '_ \/ __| '_ \ \ /\ / / '_ ` _ \ 
# | |_) \__ \ |_) \ V  V /| | | | | |
# |_.__/|___/ .__/ \_/\_/ |_| |_| |_|
#           |_|                      
#

bspc monitor HDMI-0 -d I II III IV V
bspc monitor DP-0 -d VI VII VIII IX X

bspc config focus_follows_pointer true
bspc config pointer_follows_focus false
bspc config pointer_follows_monitor true

bspc config border_width 3
bspc config window_gap 15
bspc config top_padding 40

bspc config split_ratio 0.5
# bspc config borderless_monocle true
# bspc config gapless_monocle true

bspc rule -a Pavucontrol state=floating
bspc rule -a feh state=floating
bspc rule -a firefox desktop='^1'
bspc rule -a chromium desktop='^6' follow=off
bspc rule -a discord desktop='^5' follow=off
bspc rule -a code desktop='^3' follow=off
# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off

. "${HOME}/.cache/wal/colors.sh"

bspc config normal_border_color "$color7"
bspc config active_border_color "$color7"
bspc config focused_border_color "$color1"
bspc config presel_feedback_color "$color3"

# fix cursor size
xsetroot -cursor_name left_ptr

pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x picom > /dev/null || picom --config ~/.config/picom.conf &
pgrep -x dunst > /dev/null || dunst &
pgrep -x playerctld > /dev/null || playerctld daemon &
wal -R
~/.fehbg &
~/.config/polybar/launch.sh &

